### PR TITLE
debugModeEnabled renamed to debugMode and set to true by default.

### PR DESCRIPTION
**Pull request by dreymonde**
Also, DebugLogMiddleware deleted.

### CODE REVIEW

**Comment by antonmes** [comment]
👍 maybe we could name it even shorter, just debug. @Danappelxx @paulofaria

**Comment by Danappelxx** [comment]
I wanted to wait for @paulofaria to confirm that these were his intentions, but I guess it doesn't really matter.

**Comment by paulofaria** [comment]
hahaa I already had this implemented, but I haven't pushed. I used an enum called mode with two cases `.Default` and `.Debug`, but actually this is better, more compact. if we ever have a new mode we can make it an enum. Also, I think simply `debug` is better. `true` could be the default, as well. I don't have strong opinions about that.

**Comment by paulofaria** [comment]
could someone rename to `debug` please?

**Comment by antonmes** [comment]
done

**Pull request merged**
